# Application configuration
application:
  image:
    ## TODO: Insert the registry from which you want to pull the image
    registry: "your-registry"
    repository: "demo-quarkus"
    tag: "latest"

  replicas: 2

  livenessProbe:
    url: /q/health/live

  readinessProbe:
    url: /q/health/ready

  pod:
    port: 8080

  service:
    port: 8080


# Database configuration
postgres:
  image: "docker.io/bitnami/postgresql"
  imageTag: "12.2.0"

  service:
    port: 5432


# Ingress configuration
ingress:
  host: "demo-quarkus.localhost"
