
CREATE SEQUENCE HIBERNATE_SEQUENCE START WITH 1000000;

-- *** Product catalog ***

CREATE TABLE Product
(
  id BIGSERIAL,
  modificationCounter INTEGER DEFAULT 0 NOT NULL,
  title VARCHAR (255) NOT NULL,
  description VARCHAR (4000),
  price DECIMAL (16,2) NOT NULL,
  CONSTRAINT PK_Product PRIMARY KEY(id)
);

